spring.application.name=order_management
spring.datasource.url=jdbc:postgresql://localhost:5432/order_management
spring.datasource.username = postgres
spring.datasource.password = Papaji@9611
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

